package HangmanGame;


/**
* HangmanGame/Hangman.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman.idl
* Monday, April 30, 2018 8:51:48 PM SGT
*/

public interface Hangman extends HangmanOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman
