package HangmanGame;

/**
* HangmanGame/HangmanHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman.idl
* Monday, April 30, 2018 8:51:48 PM SGT
*/

public final class HangmanHolder implements org.omg.CORBA.portable.Streamable
{
  public HangmanGame.Hangman value = null;

  public HangmanHolder ()
  {
  }

  public HangmanHolder (HangmanGame.Hangman initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HangmanGame.HangmanHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HangmanGame.HangmanHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HangmanGame.HangmanHelper.type ();
  }

}
