package HangmanGame;


/**
* HangmanGame/HangmanPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman.idl
* Monday, April 30, 2018 8:51:48 PM SGT
*/

public abstract class HangmanPOA extends org.omg.PortableServer.Servant
 implements HangmanGame.HangmanOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startGame", new java.lang.Integer (0));
    _methods.put ("getCurrentLife", new java.lang.Integer (1));
    _methods.put ("letterGuess", new java.lang.Integer (2));
    _methods.put ("newGame", new java.lang.Integer (3));
    _methods.put ("endGame", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HangmanGame/Hangman/startGame
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.startGame (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HangmanGame/Hangman/getCurrentLife
       {
         String name = in.read_string ();
         int $result = (int)0;
         $result = this.getCurrentLife (name);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // HangmanGame/Hangman/letterGuess
       {
         String name = in.read_string ();
         char letter = in.read_char ();
         boolean $result = false;
         $result = this.letterGuess (name, letter);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // HangmanGame/Hangman/newGame
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.newGame (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // HangmanGame/Hangman/endGame
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.endGame (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HangmanGame/Hangman:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hangman _this() 
  {
    return HangmanHelper.narrow(
    super._this_object());
  }

  public Hangman _this(org.omg.CORBA.ORB orb) 
  {
    return HangmanHelper.narrow(
    super._this_object(orb));
  }


} // class HangmanPOA
