package HangmanGame;


/**
* HangmanGame/HangmanOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman.idl
* Monday, April 30, 2018 10:53:54 PM SGT
*/

public interface HangmanOperations 
{
  String startGame (String name);
  int getCurrentLife (String name);
  boolean letterGuess (String name, char letter);
  String newGame (String name);
  void endGame (String name);
} // interface HangmanOperations
