

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
import HangmanGame.*;           // The package containing stubs
import org.omg.CosNaming.*;  // Client_hello will use the naming service
import org.omg.CosNaming.NamingContextPackage.*;
import org.omg.CORBA.*;      // All CORBA applications need these classes
import java.util.*;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import java.awt.*;
import java.applet.Applet;

public class HangmanUI extends javax.swing.JFrame {

    /**
     * Creates new form HangmanUI
     */
	private static String name;
	private static String word;
	private static String image = "";
	private static int life;
    private static Hangman hangman;
    private static String message = "";
    String line = "";
    
	
	
    public HangmanUI(Hangman hangman, String name, String word) {
        initComponents();
        this.hangman=hangman;
        this.name=name;
        this.word=word;
        this.message="The word is " +word+". Do you want to play again?";
        this.life=hangman.getCurrentLife(name);
        nameField.setText(name);
        for(int i = 0; i < word.length(); i++) {
          line += "_ ";
        }
        wordField.setText(line);
    }
    
    private void updateWord(String replacement){
        wordField.setText(replacement);
    }
    public void setImage(int life){
        if(life==5){
            this.image="/1.png";
        } else if(life==4){
            this.image="/2.png";
        } else if(life==3){
            this.image="/3.png";
        } else if(life==2){
            this.image="/4.png";
        } else if(life==1){
            this.image="/5.png";
        } else if(life==0){
            this.image="/6.png";
        }
    }
    private void anotherGame(){
        this.word = hangman.newGame(name);
        this.line = "";
        this.life = hangman.getCurrentLife(name);
        this.message="The word is " +word+". Do you want to play again?";
        System.out.println(word);
        for(int i = 0; i < word.length(); i++) {
          line += "_ ";
        }
        wordField.setText(line);
        aButton.setEnabled(true);
        cButton.setEnabled(true);
        bButton.setEnabled(true);
        dButton.setEnabled(true);
        eButton.setEnabled(true);
        fButton.setEnabled(true);
        gButton.setEnabled(true);
        hButton.setEnabled(true);
        iButton.setEnabled(true);
        jButton.setEnabled(true);
        kButton.setEnabled(true);
        lButton.setEnabled(true);
        nButton.setEnabled(true);
        mButton.setEnabled(true);
        oButton.setEnabled(true);
        pButton.setEnabled(true);
        qButton.setEnabled(true);
        rButton.setEnabled(true);
        sButton.setEnabled(true);
        tButton.setEnabled(true);
        uButton.setEnabled(true);
        vButton.setEnabled(true);
        wButton.setEnabled(true);
        xButton.setEnabled(true);
        yButton.setEnabled(true);
        zButton.setEnabled(true);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        aButton = new javax.swing.JButton();
        wordField = new javax.swing.JTextField();
        cButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        nameField.setEditable(false);
        wordField.setEditable(false);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Name:");

        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameField.setName(""); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        aButton.setText("A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        
        wordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);


        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        bButton.setText("B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });

        dButton.setText("D");
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });


        eButton.setText("E");
          eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });


        fButton.setText("F");
          fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });


        gButton.setText("G");
          gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });


        hButton.setText("H");
          hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });


        iButton.setText("I");
          iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });


        jButton.setText("J");
          jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });


        kButton.setText("K");
          kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });


        lButton.setText("L");
          lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });


        nButton.setText("N");
          nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });


        mButton.setText("M");
          mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });


        oButton.setText("O");
          oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });


        pButton.setText("P");
          pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });


        qButton.setText("Q");
          qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });


        rButton.setText("R");
          rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });


        sButton.setText("S");
          sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });


        tButton.setText("T");
          tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });


        uButton.setText("U");
          uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });


        vButton.setText("V");
          vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });


        wButton.setText("W");
          wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });


        xButton.setText("X");
          xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });


        yButton.setText("Y");
          yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });


        zButton.setText("Z");
          zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });


         jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2.setText("Hangman nowee-oppa Special Edition");

        jPanel1.setPreferredSize(new java.awt.Dimension(165, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(aButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oButton)
                                        .addGap(4, 4, 4)
                                        .addComponent(pButton)
                                        .addGap(6, 6, 6)))
                                .addGap(12, 12, 12))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wordField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField)))
                        .addGap(34, 34, 34)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(wordField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aButton)
                            .addComponent(bButton)
                            .addComponent(cButton)
                            .addComponent(dButton)
                            .addComponent(eButton)
                            .addComponent(fButton)
                            .addComponent(gButton)
                            .addComponent(hButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iButton)
                            .addComponent(jButton)
                            .addComponent(kButton)
                            .addComponent(lButton)
                            .addComponent(mButton)
                            .addComponent(nButton)
                            .addComponent(oButton)
                            .addComponent(pButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qButton)
                            .addComponent(rButton)
                            .addComponent(sButton)
                            .addComponent(tButton)
                            .addComponent(uButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vButton)
                            .addComponent(wButton)
                            .addComponent(xButton)
                            .addComponent(yButton)
                            .addComponent(zButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
            if(hangman.letterGuess(name, 'a')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'a') {
                    replacement += ('a' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
            this.life=hangman.getCurrentLife(name);
            setImage(life);
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));
			aButton.setEnabled(false);
            String wordGuess=line.replaceAll("\\s","");    
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }//GEN-LAST:event_aButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
         if(hangman.letterGuess(name, 'b')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'b') {
                    replacement += ('b' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		bButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");    
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }//GEN-LAST:event_bButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'c')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'c') {
                    replacement += ('c' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		cButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }//GEN-LAST:event_cButtonActionPerformed
    
    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'd')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'd') {
                    replacement += ('d' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		dButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");    
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'e')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'e') {
                    replacement += ('e' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		eButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'f')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'f') {
                    replacement += ('f' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		fButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'g')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'g') {
                    replacement += ('g' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		gButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'h')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'h') {
                    replacement += ('h' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
                    
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		hButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'i')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'i') {
                    replacement += ('i' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		iButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'j')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'j') {
                    replacement += ('j' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		jButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'k')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'k') {
                    replacement += ('k' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		kButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'l')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'l') {
                    replacement += ('l' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		lButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'm')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'm') {
                    replacement += ('m' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		mButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'n')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'n') {
                    replacement += ('n' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		nButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'o')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'o') {
                    replacement += ('o' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		oButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'p')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'p') {
                    replacement += ('p' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		pButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'q')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'q') {
                    replacement += ('q' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		qButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'r')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'r') {
                    replacement += ('r' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		rButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 's')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 's') {
                    replacement += ('s' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		sButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 't')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 't') {
                    replacement += ('t' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		tButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'u')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'u') {
                    replacement += ('u' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		uButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'v')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'v') {
                    replacement += ('v' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		vButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'w')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'w') {
                    replacement += ('w' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		wButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'x')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'x') {
                    replacement += ('x' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		xButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'y')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'y') {
                    replacement += ('y' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		yButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
         if(hangman.letterGuess(name, 'z')) {
                String replacement = "";
                for(int i = 0; i < word.length(); i++) {
                  //System.out.println(replacement);
                  if(word.charAt(i) == 'z') {
                    replacement += ('z' + " ");
                    //System.out.println(replacement);
                  } else {
                    if(i == 0) {
                      replacement += line.substring(0,2);
                      //System.out.println(replacement);
                    } else {
                      replacement += line.substring(i * 2, (i + 1) * 2);
                      //System.out.println(replacement);
                    }
                  }
                }
                this.line = replacement;
                updateWord(line);
              } else {
                // this erea can be replaced by the GUI where the line or shape can be drown;
                System.out.println(life);
              }
        this.life=hangman.getCurrentLife(name);
        setImage(life);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(image)));        // TODO add your handling code here:
		zButton.setEnabled(false);
        String wordGuess=line.replaceAll("\\s","");     
        if(wordGuess.equals(word)){
                this.life=0;
                this.message="Congrats! Do you want to play again?";
            }
            if(life==0){
                int reply = JOptionPane.showConfirmDialog(null, message, "Game over", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                  anotherGame();
                }
                else {
                   JOptionPane.showMessageDialog(null, "Thanks For playing");
                   hangman.endGame(name);
                    System.exit(0);
                }
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanUI(hangman,name,word).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton dButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton fButton;
    private javax.swing.JButton gButton;
    private javax.swing.JButton hButton;
    private javax.swing.JButton iButton;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JButton mButton;
    private javax.swing.JButton nButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton sButton;
    private javax.swing.JButton tButton;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JTextField wordField;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
