module HangmanGame
{
  interface Hangman
  {
    string startGame(in string name);
    long getCurrentLife(in string name);
    boolean letterGuess(in string name, in char letter);
    string newGame(in string name);
    void endGame(in string name);
  };
};
